server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hunters_db
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl